build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fancy-namer"
version = "0.1.0"
description = "A fancy name generator"
authors = [
    {name = "Carlos Gustavo Lopez Pombo", email = "clpombo@gmail.com"}
]
requires-python = ">=3.12"
dependencies = []

[tool.setuptools.packages.find]
where = ["."]
include = ["fancy_namer*"]